name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GStreamer
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends --no-install-suggests \
            libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev

    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2

    - name: Check formatting
      run: cargo fmt --check

    - name: Run clippy
      run: cargo clippy -- -D warnings

    - name: Run unit tests
      run: cargo test --quiet --bins

    # Integration tests work locally but hang in CI due to environment restrictions
    # - name: Run integration tests
    #   run: cargo test --quiet --test integration_test -- --test-threads=1 --nocapture
    #   timeout-minutes: 3

    - name: Build release
      run: cargo build --release --quiet
